include(CheckCXXCompilerFlag)

macro(check_and_add_cxx_flags flag)
	string(REGEX REPLACE "-" "" var1 "Compiler_Has_${flag}_Flag")
	string(REGEX REPLACE "\\+" "p" var2 ${var1})
	string(REGEX REPLACE "=" "" var ${var2})
	check_cxx_compiler_flag(${flag} ${var})
	if (${var})
		set(MY_CUSTOM_CXX_FLAGS ${MY_CUSTOM_CXX_FLAGS} ${flag})
	endif()
endmacro()

include(CheckCCompilerFlag)

macro(check_and_add_c_flags flag)
	string(REGEX REPLACE "-" "" var1 "Compiler_Has_${flag}_Flag")
	string(REGEX REPLACE "\\+" "p" var2 ${var1})
	string(REGEX REPLACE "=" "" var ${var2})
	check_c_compiler_flag(${flag} ${var})
	if (${var})
		set(MY_CUSTOM_C_FLAGS ${MY_CUSTOM_C_FLAGS} ${flag})
	endif()
endmacro()

include(CheckFortranCompilerFlag)

macro(check_and_add_fortran_flags flag)
	string(REGEX REPLACE "-" "" var1 "Compiler_Has_${flag}_Flag")
	string(REGEX REPLACE "\\+" "p" var2 ${var1})
	string(REGEX REPLACE "=" "" var ${var2})
	check_fortran_compiler_flag(${flag} ${var})
	if (${var})
		set(MY_CUSTOM_Fortran_FLAGS ${MY_CUSTOM_Fortran_FLAGS} ${flag})
	endif()
endmacro()
